services:
  back-end:
    build:
      context: smellsViz/backend
      dockerfile: Dockerfile
    # image: kevinpanchal/${TYPE}-viz-backend
    working_dir: /usr/src/app
    networks:
      - kevin
    volumes:
      - "${FOLDER}:/usr/src/app/smells"
    tty: true
    ports:
      - "3001:3001"

  front-end:
    build:
      context: smellsViz/frontend
      dockerfile: Dockerfile
    # image: kevinpanchal/${TYPE}-viz-frontend
    working_dir: /usr/src/app
    networks:
      - kevin
    ports:
      - "3000:3000"

networks:
  kevin:
    driver: bridge
