services:
  back-end:
    build:
      context: ${MODE}/backend
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    networks:
      - dj
    volumes:
      - "${FOLDER}:/usr/src/app/smells"
    tty: true
    ports:
      - "3001:3001"

  front-end:
    build:
      context: ${MODE}/frontend
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    networks:
      - dj
    ports:
      - "3000:3000"

networks:
  dj:
    driver: bridge
